### ISSUE TITLE
STS Patch Broke this mod

### ISSUE THREAD

**Issue by Peppe-KSP** [Jazzer360/sts-weighted-paths#1]
Missing class reference of STSSentry.

import com.megacrit.cardcrawl.core.STSSentry; 

Is no longer in the base game as far as I can tell.

Looks like you only used it to find  the hostname?  

Maybe InetAddress.getLocalHost().getHostName() can do the same?

Not sure if it matters but pom.xml basemod I think the groupid is:
 <groupId>basemod</groupId>

**Comment by Peppe-KSP** [comment]
PR Test: https://github.com/Jazzer360/sts-weighted-paths/pull/2

**Comment by Jazzer360** [comment]
Implemented the fix
